import Head from "next/head";

import Nav from "../../components/ui/nav.ui";
import Footer from "../../components/ui/footer.ui";
import Typography from "../../components/Typography.component";
import ArticleBox from "../../components/article-box.component";

const fakePosts = [
  {
    id: 1,
    title: "Top 15 Must Read Team Leadership Blogs",
    description:
      "Innovation and a growing number of specialized workers means that leadership itself is becoming a specialized skill. The road to success is...",
    auther: "John McMan",
    date: "25 November, 2020",
    avatar: "/avatars/John McMan.jpg",
    photo: "/post images/1.jpg",
  },
  {
    id: 2,
    title: "Importance of Communication in Teamwork",
    description:
      "Under the assignment of responding other’s blog post, I read some blogs about teamwork. Then, I have some ideas of teamwork due to one of...",
    auther: "Scarlett Geller",
    date: "20 Febreuary, 2021",
    avatar: "/avatars/Scarlett Geller.jpg",
    photo: "/post images/2.jpeg",
  },
  {
    id: 3,
    title: "Which one is better, teamwork or working independently?",
    description:
      "In the business world, people have two ways to organize their working style: working independently and teamwork.",
    auther: "Darwen Green",
    date: "09 March, 2020",
    avatar: "/avatars/Darwen Green.jpg",
    photo: "/post images/3.png",
  },
  {
    id: 4,
    title: "How to be a good team member?",
    description:
      "Last week, I found a helpful book, “When Teams Work Best” written by Frank LaFasto and Carl Larson in 2001, in UB library to make a whole picture of teamwork...",
    auther: "Monica Black",
    date: "05 May, 2019",
    avatar: "/avatars/Monica Black.jpg",
    photo: "/post images/4.png",
  },
  {
    id: 5,
    title: "How to build effective cross-team collaboration",
    description:
      "Effective cross-team collaboration is no less important than collective work inside the team. Without such a collaboration company...",
    auther: "Lara Larson",
    date: "29 October, 2020",
    avatar: "/avatars/Lara Larson.jpg",
    photo: "/post images/5.jpeg",
  },
  {
    id: 6,
    title: "Importance of effective collaboration for team productivity",
    description:
      "A collaborative team is much more effective than a hierarchical team. In a hierarchical team, there is a leader or captain who guides the...",
    auther: "Mark Edward",
    date: "21 December, 20219",
    avatar: "/avatars/Mark Edward.jpg",
    photo: "/post images/1.jpg",
  },
];

const BlogPage = () => (
  <div className="bg-grey-light overflow-x-hidden">
    <Head>
      <title>Team App | Blog Post</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Nav theme="dark" />
      <div className="max-w-1160 px-4 mx-auto mt-36">
        <Typography variant="h1" className="text-blue-dark">
          Blog
        </Typography>
        <Typography variant="p" className="text-grey-dark mt-5">
          Our thoughts, insights and ideas. We’re trying to make your experience
          perfect.
        </Typography>
        <div className="grid grid-flow-row grid-cols-3 gap-7 my-16 lg:grid-cols-2 sm:grid-cols-1">
          {fakePosts.map((post) => (
            <ArticleBox {...post} />
          ))}
        </div>
      </div>
    </main>
    <Footer />
  </div>
);

export default BlogPage;
