import Head from "next/head";

import Nav from "../components/ui/nav.ui";
import Footer from "../components/ui/footer.ui";
import HeroSection from "../components/ui/hero-section.ui";
import FirstSection from "../components/ui/first-section.ui";
import RatingSection from "../components/ui/rating-section.ui";
import FeaturesSection from "../components/ui/features-section.ui";

export default function Home() {
  return (
    <div className="bg-grey-light overflow-x-hidden">
      <Head>
        <title>Team App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <HeroSection />
        <FirstSection />
        <FeaturesSection />
        <RatingSection />
      </main>
      <Footer />
    </div>
  );
}
